### ISSUE TITLE
Malformed GnuHashHeader causes 'attempt to calculate the remainder with a divisor of zero' in hash.rs:276:33

### ISSUE THREAD

**Issue by chaostheory88** [cole14/rust-elf#25]
Hi! While fuzzing found a panic providing the `BUF` input in the sample program below:

```rust
use elf::endian::AnyEndian;
use elf::ElfBytes;

const BUF: [u8; 328] = [
    127, 69, 76, 70, 2, 1, 1, 255, 69, 1, 10, 255, 0, 0, 0, 0, 1, 228, 98, 1, 1, 1, 1, 70, 1, 76,
    252, 128, 254, 186, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 68, 0, 0, 0, 0, 0, 0, 0, 126, 0, 0, 0, 0, 0,
    0, 4, 0, 0, 64, 0, 4, 0, 0, 31, 0, 0, 0, 0, 1, 0, 0, 1, 246, 255, 255, 111, 1, 70, 1, 247, 1,
    1, 1, 1, 70, 76, 0, 127, 1, 197, 17, 0, 0, 1, 0, 0, 0, 0, 0, 0, 70, 0, 0, 0, 0, 0, 0, 0, 122,
    76, 127, 70, 1, 1, 61, 1, 1, 1, 0, 0, 67, 0, 0, 0, 0, 0, 0, 69, 76, 70, 255, 246, 149, 149, 0,
    1, 11, 0, 0, 0, 246, 255, 255, 111, 1, 70, 1, 1, 1, 3, 1, 1, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0,
    0, 244, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 68, 0, 0, 0, 0, 0, 0, 5, 122, 0, 255, 246, 24, 0, 0,
    0, 0, 0, 0, 0, 4, 0, 0, 64, 0, 4, 0, 0, 127, 122, 76, 127, 193, 254, 2, 0, 63, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 195, 0, 122, 0, 0, 143, 143, 255, 255, 129, 193, 76, 70, 2, 1, 1, 5, 243, 0, 0,
    255, 255, 0, 255, 0, 1, 228, 96, 1, 1, 1, 1, 0, 0, 7, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 68, 0, 0, 0, 0, 0, 0, 0, 126, 0, 0, 112, 255, 255, 246, 4, 0, 0, 64, 0, 4, 0, 0, 255, 255,
    1, 78, 0, 0, 1, 228, 96, 1, 1, 1, 1, 1, 70, 76, 142, 0, 127, 1, 4, 0, 0, 64, 93, 4, 0, 0, 127,
    122, 67, 0, 0, 0,
];

fn main() {
    if let Ok(file) = ElfBytes::<AnyEndian>::minimal_parse(&BUF) {
        if let Ok(common) = file.find_common_data() {
            // parse the dynamic symbol table
            if let Some(dynsyms) = common.dynsyms {
                if let Some(dynstrs) = common.dynsyms_strs {
                    let sym_names: Vec<&[u8]> = dynsyms
                        .iter()
                        .map(|sym| dynstrs.get_raw(sym.st_name as usize).unwrap_or(b"unk"))
                        .collect();

                    // use the gnu hash table
                    if let Some(hash) = common.gnu_hash {
                        for name in sym_names.iter() {
                            let _ = hash.find(name, &dynsyms, &dynstrs);
                        }
                    }
                }
            }
        }
    }
}
```

Panic message:
```text
thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', /home/fbrx/.cargo/registry/src/github.com-1ecc6299db9ec823/elf-0.7.0/src/hash.rs:276:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:115:5
   3: elf::hash::GnuHashTable<E>::find
             at /home/fbrx/.cargo/registry/src/github.com-1ecc6299db9ec823/elf-0.7.0/src/hash.rs:276:33
   4: elf_crash::main
             at ./src/main.rs:34:37
   5: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

Panic happens here: https://github.com/cole14/rust-elf/blob/master/src/hash.rs#L276. If I understood it correctly,  while parsing a `GnuHashHeader` here: https://github.com/cole14/rust-elf/blob/master/src/hash.rs#L164, it happens that value for `nbloom` at that offset is 0, this will later cause the panic.

Thanks!

**Comment by cole14** [comment]
Awesome, thanks for the report! I'll have some time to fix this later in the week, and am also open to a PR if you have some time :)
